# Generated by Django 5.0.5 on 2024-05-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oddamApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.IntegerField(choices=[(1, 'Fundacja'), (2, 'Organizacja pozarządowa'), (3, 'Zbiórka lokalna')], default=1),
        ),
    ]
