# Generated by Django 5.0.5 on 2024-05-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oddamApp', '0002_alter_institution_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
